name: Run Script

on:
  workflow_dispatch:
    inputs:
      run_github_account:
        description: 'GitHub Account Owner'
        required: true
        default: 'mwinokan'
      run_repo_github:
        description: 'repo-name'
        required: true
        default: 'ToiletFPL' 
  schedule:
    - cron: '00 07 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.TOILET_ACTION }}
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytz mpytools pandas matplotlib numpy plotly markdown scipy requests
      - name: execute py script # run file
        run: |
          python wiki.py
      - name: push changes
        run: |
          git config --global user.name 'Max Winokan'
          git config --global user.email 'mwinokan@me.com'
          git commit -am `date +%s`
          git push
