name: Run Script

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - uses: jannekem/run-python-script-action@v1
        with:
          script: |
            import os
            import sys
            import pprint
            sys.path.append(os.path.join(os.path.dirname(__file__)))
            pprint.pprint(sys.path)
            from wiki import main
            main()
