name: Run Script

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytz mpytools pandas matplotlib numpy plotly markdown scipy requests
      - name: execute py script # run file
        run: |
          python wiki.py --offline
      - name: push changes
        run: |
          git config --global user.name 'Max Winokan'
          git config --global user.email 'your-username@users.noreply.github.com'
          git commit -am `date +%s`
          git push
