name: Run Script

on:
  workflow_dispatch:
    inputs:
      run_message:
        description: 'This does nothing'
        required: true
        default: 'Manual run' 
  schedule:
    - cron: '00 07-23 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.TOILET_ACTION }}
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytz mpytools pandas matplotlib numpy plotly markdown scipy requests tqdm IPython cairosvg
      - name: execute py script # run file
        run: |
          python wiki.py
      - name: push changes
        run: |
          git add *txt
          git config --global user.name 'Max Winokan'
          git config --global user.email 'mwinokan@me.com'
          git commit -am `date +%s`
          git push
